define([], function() {
  return {
    "Title": "PlanMyDayApplicationCustomizer",
    "LauncherButtonLabel": "Plan My Day",
    "PanelTitle": "Plan My Day",
    "RefreshButtonLabel": "Refresh",
    "CloseButtonLabel": "Close",
    "GreetingMorning": "Good morning, {0}!",
    "GreetingAfternoon": "Good afternoon, {0}!",
    "GreetingEvening": "Good evening, {0}!",
    "AgendaSectionTitle": "Today's agenda",
    "AgendaEmpty": "No more meetings today.",
    "AgendaJoinButton": "Join",
    "TasksSectionTitle": "Tasks due",
    "TasksEmpty": "Nothing due \u2014 you're all caught up.",
    "TasksMarkComplete": "Mark complete",
    "EmailsSectionTitle": "Important emails",
    "EmailsEmpty": "No high-importance emails.",
    "NewsSectionTitle": "Latest news",
    "NewsEmpty": "No recent news posts.",
    "QuickActionsSectionTitle": "Quick actions",
    "QuickActionJoinNextMeeting": "Join next meeting",
    "QuickActionNoMeeting": "No upcoming meeting",
    "QuickActionMarkTaskComplete": "Mark next task complete",
    "QuickActionNoTask": "No tasks due",
    "CopilotSectionTitle": "Ask Copilot",
    "CopilotPlaceholder": "Search your files and content...",
    "CopilotSubmit": "Ask",
    "CopilotLoading": "Thinking...",
    "CopilotResultsCount": "Showing {0} of {1} results",
    "CopilotNoResults": "No matching content found.",
    "CopilotError": "Copilot couldn't answer that. Please try again.",
    "CopilotLicenseError": "This feature requires a Microsoft 365 Copilot license.",
    "LoadingLabel": "Loading...",
    "ErrorLabel": "Something went wrong loading this section.",
    "MockDataBanner": "Showing sample data (mock mode)"
  }
});